borrar(_,[],[]). 
borrar(E,[H|T],T):- E = H.
borrar(E,[H|T],[H|R]):- borrar(E,T,R).

/*EL BORRAR ES LA MISMA COSA SOLAMENTE QUE AHORA SE PREGUNTA CUANDO ES IGUAL Y SI LO ES DEVERÍA DEVOLVER LA LISTA SIN LA CABEZA (QUE ES EL ELEMENTO A BORRAR JUSTAMENTE)*/
