(define (transpose lista)
  (append (list (map (lambda (x)
                       (car x)
                       )
                     lista)
                )
          (map (lambda (x)
                 (car (cdr x))
                 )
               lista)
          )
  )

(transpose '((a 1) (b 2) (c 3)))